  sonar.projectKey=nodejs-sonarqube-setup-with-github-action
  sonar.organization=rupachowrasia
  sonar.host.url=https://sonarcloud.io
  sonar.login=${SONAR_TOKEN}
  sonar.sources=.
  sonar.language=js